### ISSUE TITLE
unmonitor_downloaded_episodes.py gives error and can't save

### ISSUE THREAD

**Issue by vanth0me** [Casvt/Plex-scripts#8]
Have not pressed test, also fails on pressing save. Sonarr version: 3.0.6.1342 on Windows 10.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/28623044/151701906-6465a9ba-ca90-4374-8523-6b773c614620.png)

**Comment by Casvt** [comment]
Noted.

Already know what it is. I'll be home in a few hours and will fix it.

**Comment by Casvt** [comment]
Script is fixed. Please re-grab it and try again; it should work now. When I developed the script, you were able to save a script without the need to have a successful test. Now you do apparently, so I added support for the script to be tested by Sonarr and report correctly based on if the script is setup correctly. Assuming that you set it up correctly (it's hard to _not_ set it up correctly), it will now return successful when you click 'test' which will enable you to add it.

Please let me know if it's working now so that I can close the issue.

**Comment by vanth0me** [comment]
Sorry for the late response. Tried it again and it still failed, maybe it has something to do with the assigning of the variables?

**Comment by Casvt** [comment]
Can you share the values of the variables inside the file?

**Comment by vanth0me** [comment]
I think I'm starting to see the issue. I thought the variables would be assigned in the script because sonarr runs it. Now I start to think I might need to do this myself. Give me a second to try this.

**Comment by Casvt** [comment]
Yeah maybe it's smarter to adapt the script to get the info from environment variables instead of from manually set values. Either way, good to hear that it's working now.
